/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on May 23, 2010, 7:36:32 PM
 */

package org.tridas.io.gui.view.main;

/**
 *
 * @author daniel
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        inputFormat = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        removeSelectedButton = new javax.swing.JButton();
        selectLabel = new javax.swing.JLabel();
        selectAllButton = new javax.swing.JButton();
        selectNoneButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        namingConvention = new javax.swing.JComboBox();
        outputFormat = new javax.swing.JComboBox();
        convertButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        convertedTree = new javax.swing.JTree();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuButton = new javax.swing.JMenuItem();
        saveMenuButton = new javax.swing.JMenuItem();
        quitMenuButton = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        tabbedPane.setName("jTabbedPane1"); // NOI18N

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        addButton.setText(("jButton1.text")); // NOI18N
        addButton.setName("jButton1"); // NOI18N
        jPanel4.add(addButton);

        inputFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inputFormat.setName("jComboBox1"); // NOI18N
        jPanel4.add(inputFormat);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        fileList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fileList.setName("jList1"); // NOI18N
        jScrollPane3.setViewportView(fileList);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        removeSelectedButton.setText(("jButton7.text")); // NOI18N
        removeSelectedButton.setName("jButton7"); // NOI18N
        jPanel3.add(removeSelectedButton);

        selectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectLabel.setText(("jLabel4.text")); // NOI18N
        selectLabel.setName("jLabel4"); // NOI18N
        jPanel3.add(selectLabel);

        selectAllButton.setText(("jButton5.text")); // NOI18N
        selectAllButton.setName("jButton5"); // NOI18N
        jPanel3.add(selectAllButton);

        selectNoneButton.setText(("jButton6.text")); // NOI18N
        selectNoneButton.setName("jButton6"); // NOI18N
        jPanel3.add(selectNoneButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        tabbedPane.addTab(("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        namingConvention.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        namingConvention.setName("jComboBox3"); // NOI18N
        jPanel6.add(namingConvention);

        outputFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        outputFormat.setName("jComboBox2"); // NOI18N
        jPanel6.add(outputFormat);

        convertButton.setText(("jButton3.text")); // NOI18N
        convertButton.setName("jButton3"); // NOI18N
        jPanel6.add(convertButton);

        saveButton.setText(("jButton2.text")); // NOI18N
        saveButton.setName("jButton2"); // NOI18N
        jPanel6.add(saveButton);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        convertedTree.setName("jTree1"); // NOI18N
        jScrollPane1.setViewportView(convertedTree);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab(("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        menuBar.setName("jMenuBar1"); // NOI18N

        fileMenu.setText(("jMenu1.text")); // NOI18N
        fileMenu.setName("jMenu1"); // NOI18N

        loadMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadMenuButton.setText(("jMenuItem1.text")); // NOI18N
        loadMenuButton.setName("jMenuItem1"); // NOI18N
        fileMenu.add(loadMenuButton);

        saveMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuButton.setText(("jMenuItem4.text")); // NOI18N
        saveMenuButton.setName("jMenuItem4"); // NOI18N
        fileMenu.add(saveMenuButton);

        quitMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitMenuButton.setText(("jMenuItem2.text")); // NOI18N
        quitMenuButton.setName("jMenuItem2"); // NOI18N
        fileMenu.add(quitMenuButton);

        menuBar.add(fileMenu);

        helpMenu.setText(("jMenu2.text")); // NOI18N
        helpMenu.setName("jMenu2"); // NOI18N

        aboutMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenuButton.setText(("jMenuItem3.text")); // NOI18N
        aboutMenuButton.setName("jMenuItem3"); // NOI18N
        helpMenu.add(aboutMenuButton);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JButton selectNoneButton;
    private javax.swing.JButton removeSelectedButton;
    private javax.swing.JComboBox inputFormat;
    private javax.swing.JComboBox outputFormat;
    private javax.swing.JComboBox namingConvention;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JList fileList;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem loadMenuButton;
    private javax.swing.JMenuItem quitMenuButton;
    private javax.swing.JMenuItem aboutMenuButton;
    private javax.swing.JMenuItem saveMenuButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTree convertedTree;
    // End of variables declaration//GEN-END:variables

}
